#ifndef __MULTI_LINK_KEYBOARD_H__
#define __MULTI_LINK_KEYBOARD_H__

#include <stdbool.h>
#include <stdint.h>
#include "multi_link.h"

#define M_KEYBOARD_MAX_NUM_KEYS 6 

typedef enum
{
    KEY_EVT_PAIR_BTN_PRESSED,
    KEY_EVT_PAIR_BTN_RELEASED,
    KEY_EVT_TEST_MODE,
    KEY_EVT_INFO,
    
    KEY_EVT_HOST_NAME,
    KEY_EVT_FW_VER,
    KEY_EVT_BAT_LEVEL,
  
    KEY_EVT_NORMAL_KEY,
    KEY_EVT_COMSUMER_KEY,
    KEY_EVT_FN_LOCK,  
  
    KEY_EVT_OOB
  
}key_evt_t;

 
/**@brief Data type generated by this module.  */
typedef struct
{
    key_evt_t     key_evt_type; 
    uint8_t       modifier_keys;
    uint8_t       reserve;
    uint8_t       keys[M_KEYBOARD_MAX_NUM_KEYS];

    uint8_t       fn_pressed:1;
    uint8_t       fn_lock:1;
    uint8_t       num_keys;
} m_keyboard_data_t; 
 
#endif /* __MULTI_LINK_KEYBOARD_H__ */

