#ifndef ZEPHYR_INCLUDE_DRIVERS_LED_LP50XX_H_
#define ZEPHYR_INCLUDE_DRIVERS_LED_LP50XX_H_

#define LP50XX_MAX_LEDS		12
#define LP50XX_COLORS_PER_LED	1//3

/*
 * LED channels mapping.
 */

#define LP50XX_NUM_CHANNELS	52

/* Bank channels. */
#define LP50XX_BANK_CHAN_BASE		0
#define LP50XX_BANK_BRIGHT_CHAN		LP50XX_BANK_CHAN_BASE
#define LP50XX_BANK_COL1_CHAN(led)	(LP50XX_BANK_CHAN_BASE + 1)
#define LP50XX_BANK_COL2_CHAN(led)	(LP50XX_BANK_CHAN_BASE + 2)
#define LP50XX_BANK_COL3_CHAN(led)	(LP50XX_BANK_CHAN_BASE + 3)

/* LED brightness channels. */
#define LP50XX_LED_BRIGHT_CHAN_BASE	4
#define LP50XX_LED_BRIGHT_CHAN(led)	(LP50XX_LED_BRIGHT_CHAN_BASE + led)

/* LED color channels. */
#define LP50XX_LED_COL_CHAN_BASE	16
#define LP50XX_LED_COL1_CHAN(led)	(LP50XX_LED_COL_CHAN_BASE + \
					 led * LP50XX_COLORS_PER_LED)
#define LP50XX_LED_COL2_CHAN(led)	(LP50XX_LED_COL_CHAN_BASE + \
					 led * LP50XX_COLORS_PER_LED + 1)
#define LP50XX_LED_COL3_CHAN(led)	(LP50XX_LED_COL_CHAN_BASE + \
					 led * LP50XX_COLORS_PER_LED + 2)

#endif /* ZEPHYR_INCLUDE_DRIVERS_LED_LP50XX_H_ */
