/*
 * Copyright (c) 2024 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#include "hid_keymap.h"
#include <caf/key_id.h>
#include "usb_usage.h"
#include "fn_key_id.h"
#ifdef CONFIG_DPM_COLLABS_KEY_SUPPORT
#include "collabs_key_id.h"
#endif
#ifdef CONFIG_DESKTOP_MAC_OS_KEYS_ENABLE
#include "mac_os_key_id.h"
#endif
/* This configuration file is included only once from hid_state module and holds
 * information about mapping between buttons and generated reports.
 */

/* This structure enforces the header file is included only once in the build.
 * Violating this requirement triggers a multiple definition error at link time.
 */
const struct {} hid_keymap_def_include_once;

/*
 * HID keymap. The Consumer Control keys are defined in section 15 of
 * the HID Usage Tables document under the following URL:
 * https://www.usb.org/sites/default/files/hut1_12.pdf
 */
static const struct hid_keymap hid_keymap[] = {
    { KEY_ID(0x00, 0x00), USAGE_ID_P,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x00, 0x01), USAGE_ID_LEFT_BRACKET,    REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x00, 0x02), USAGE_ID_A,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x00, 0x03), USAGE_ID_RIGHT_BRACKET,   REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x00, 0x04), USAGE_ID_BACKSPACE,       REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x00, 0x05), USAGE_ID_KP_1,            REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x00, 0x06), USAGE_ID_U,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x00, 0x07), USAGE_ID_RIGHT_ARROW,     REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x00, 0x08), USAGE_ID_INTL_2,          REPORT_ID_KEYBOARD_KEYS },  //k133
	{ KEY_ID(0x00, 0x09), USAGE_ID_I,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x00, 0x0A), USAGE_ID_LEFT_ARROW,      REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x00, 0x0B), USAGE_ID_CAPS_LOCK,       REPORT_ID_KEYBOARD_KEYS },

    { KEY_ID(0x01, 0x00), USAGE_ID_F7,              REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x01, 0x01), USAGE_ID_F9,              REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x01, 0x02), USAGE_ID_F1,              REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x01, 0x03), USAGE_ID_F11,             REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x01, 0x04), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x01, 0x05), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x01, 0x06), USAGE_ID_F5, REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x01, 0x07), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },  //mode key
//	{ KEY_ID(0x01, 0x08), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x01, 0x09), USAGE_ID_F3, REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x01, 0x0A), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x01, 0x0B), USAGE_ID_ESCAPE,          REPORT_ID_KEYBOARD_KEYS },

    { KEY_ID(0x02, 0x00), USAGE_ID_F8,              REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x02, 0x01), USAGE_ID_F10,             REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x02, 0x02), USAGE_ID_F4,              REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x02, 0x03), USAGE_ID_F12,             REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x02, 0x04), USAGE_ID_PAUSE,           REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x02, 0x05), USAGE_ID_KP_COMMA,        REPORT_ID_KEYBOARD_KEYS },  //K107
	{ KEY_ID(0x02, 0x06), USAGE_ID_F6,              REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x02, 0x07), USAGE_ID_DELETE,  		REPORT_ID_KEYBOARD_KEYS },  /*Collabs Sharing Screen / CE*/
	{ KEY_ID(0x02, 0x08), USAGE_ID_KP_ENTER,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x02, 0x09), USAGE_ID_Q,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x02, 0x0A), USAGE_ID_F9,              REPORT_ID_KEYBOARD_KEYS },  /*Collabs Chat / +/-*/
	{ KEY_ID(0x02, 0x0B), USAGE_ID_F2,              REPORT_ID_KEYBOARD_KEYS },

    { KEY_ID(0x03, 0x00), USAGE_ID_MINUS,           REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x03, 0x01), USAGE_ID_EQUAL,           REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x03, 0x02), USAGE_ID_2,               REPORT_ID_KEYBOARD_KEYS },
    { KEY_ID(0x03, 0x03), USAGE_ID_INTL_3,          REPORT_ID_KEYBOARD_KEYS },  //K14
	{ KEY_ID(0x03, 0x04), USAGE_ID_L,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x03, 0x05), USAGE_ID_KP_4,            REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x03, 0x06), USAGE_ID_6,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x03, 0x07), USAGE_ID_KP_5,            REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x03, 0x08), USAGE_ID_KP_8,            REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x03, 0x09), USAGE_ID_W,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x03, 0x0A), USAGE_ID_KP_6,            REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x03, 0x0B), USAGE_ID_ACCENT,          REPORT_ID_KEYBOARD_KEYS },

    { KEY_ID(0x04, 0x00), USAGE_ID_8,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x04, 0x01), USAGE_ID_0,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x04, 0x02), USAGE_ID_TAB,             REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x04, 0x03), USAGE_ID_INSERT,          REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x04, 0x04), USAGE_ID_HOME,            REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x04, 0x05), USAGE_ID_PAGE_UP,         REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x04, 0x06), USAGE_ID_D,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x04, 0x07), USAGE_ID_NUM_LOCK,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x04, 0x08), USAGE_ID_KP_ASTERISK,     REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x04, 0x09), USAGE_ID_F,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x04, 0x0A), USAGE_ID_KP_PLUS,         REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x04, 0x0B), USAGE_ID_1,               REPORT_ID_KEYBOARD_KEYS },

    { KEY_ID(0x05, 0x00), USAGE_ID_7,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x05, 0x01), USAGE_ID_9,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x05, 0x02), USAGE_ID_3,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x05, 0x03), USAGE_ID_DELETE,          REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x05, 0x04), USAGE_ID_END,             REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x05, 0x05), USAGE_ID_PAGE_DOWN,       REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x05, 0x06), USAGE_ID_5,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x05, 0x07), USAGE_ID_KP_7,            REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x05, 0x08), USAGE_ID_KP_9,            REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x05, 0x09), USAGE_ID_E,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x05, 0x0A), USAGE_ID_KP_MINUS,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x05, 0x0B), USAGE_ID_4,               REPORT_ID_KEYBOARD_KEYS },

    { KEY_ID(0x06, 0x00), USAGE_ID_O,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x06, 0x01), USAGE_ID_NON_US_HASH,     REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x06, 0x02), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x06, 0x03), USAGE_ID_BACK_SLASH,      REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x06, 0x04), USAGE_ID_KP_0,            REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x06, 0x05), USAGE_ID_UP_ARROW,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x06, 0x06), USAGE_ID_Y,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x06, 0x07), USAGE_ID_KP_2,            REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x06, 0x08), USAGE_ID_KP_3,            REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x06, 0x09), USAGE_ID_R,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x06, 0x0A), USAGE_ID_KP_DOT,          REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x06, 0x0B), USAGE_ID_S,               REPORT_ID_KEYBOARD_KEYS },

    { KEY_ID(0x07, 0x00), USAGE_ID_G,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x07, 0x01), USAGE_ID_H,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x07, 0x02), USAGE_ID_Z,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x07, 0x03), USAGE_ID_J,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x07, 0x04), USAGE_ID_LANG_2,          REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x07, 0x05), USAGE_ID_LANG_1,          REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x07, 0x06), USAGE_ID_T,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x07, 0x07), USAGE_ID_LANG_5,          REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x07, 0x08), USAGE_ID_DOWN_ARROW,      REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x07, 0x09), USAGE_ID_BACK_SLASH,      REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x07, 0x0A), USAGE_ID_KP_SLASH,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x07, 0x0B), USAGE_ID_F16,             REPORT_ID_KEYBOARD_KEYS },  //FN

    { KEY_ID(0x08, 0x00), USAGE_ID_SEMICOLON,       REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x08, 0x01), USAGE_ID_V,               REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x08, 0x02), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x08, 0x03), USAGE_ID_ENTER,           REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x08, 0x04), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x08, 0x05), USAGE_ID_RIGHT_CTL,       REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x08, 0x06), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x08, 0x07), USAGE_ID_LANG_4,          REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x08, 0x08), 0x0192,             		REPORT_ID_CONSUMER_CTRL },  /* Collabs Video / Caculator*/
	{ KEY_ID(0x08, 0x09), USAGE_ID_LEFT_CTL,        REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x08, 0x0A), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x08, 0x0B), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },

    { KEY_ID(0x09, 0x00), USAGE_ID_C,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x09, 0x01), USAGE_ID_QUOTE,           REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x09, 0x02), USAGE_ID_LEFT_SHIFT,      REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x09, 0x03), USAGE_ID_N,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x09, 0x04), USAGE_ID_K,               REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x09, 0x05), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x09, 0x06), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x09, 0x07), USAGE_ID_M,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x09, 0x08), USAGE_ID_RIGHT_SHIFT,     REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x09, 0x09), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x09, 0x0A), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x09, 0x0B), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },

    { KEY_ID(0x0A, 0x00), USAGE_ID_X,               REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0A, 0x01), USAGE_ID_STOP_AND_GREATER,REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0A, 0x02), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0A, 0x03), USAGE_ID_SCROLL_LOCK,     REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0A, 0x04), USAGE_ID_PRINT_SCREEN,    REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x0A, 0x05), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x0A, 0x06), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0A, 0x07), USAGE_ID_APPLICATION,     REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x0A, 0x08), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x0A, 0x09), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x0A, 0x0A), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0A, 0x0B), USAGE_ID_LEFT_GUI,        REPORT_ID_KEYBOARD_KEYS },

    { KEY_ID(0x0B, 0x00), USAGE_ID_SLASH,           REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0B, 0x01), USAGE_ID_B,               REPORT_ID_KEYBOARD_KEYS },
	//{ KEY_ID(0x0B, 0x02), USAGE_ID_NO_EVENT,      REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0B, 0x03), USAGE_ID_COMMA,           REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0B, 0x04), USAGE_ID_SPACEBAR,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0B, 0x05), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0B, 0x06), USAGE_ID_LEFT_ALT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0B, 0x07), USAGE_ID_LANG_4,          REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0B, 0x08), USAGE_ID_APPLICATION,     REPORT_ID_KEYBOARD_KEYS },  /*collabs mic mute / app*/
//	{ KEY_ID(0x0B, 0x09), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0B, 0x0A), USAGE_ID_RIGHT_ALT,       REPORT_ID_KEYBOARD_KEYS },
//	{ KEY_ID(0x0B, 0x0B), USAGE_ID_NO_EVENT,        REPORT_ID_KEYBOARD_KEYS },

/******************************************for combo key use*********************************************/
	{ KEY_ID(0x0C, 0x00), USAGE_ID_F13,        		REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0C, 0x01), USAGE_ID_F14,        		REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0C, 0x02), USAGE_ID_F15,        		REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0C, 0x03), USAGE_ID_F16,        		REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0C, 0x04), USAGE_ID_F17,        		REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0C, 0x05), USAGE_ID_F18,        		REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0C, 0x06), USAGE_ID_F19,        		REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0C, 0x07), USAGE_ID_F20,        		REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0C, 0x08), USAGE_ID_F21,        		REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0C, 0x09), USAGE_ID_F22,        		REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0C, 0x0A), USAGE_ID_F23,        		REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0C, 0x0B), USAGE_ID_F24,        		REPORT_ID_KEYBOARD_KEYS },
	{ KEY_ID(0x0C, 0x0C), USAGE_ID_LEFT_GUI,        REPORT_ID_KEYBOARD_KEYS },
/******************************************for combo key use*********************************************/
#if CONFIG_DESKTOP_FN_KEYS_ENABLE
	{ FN_KEY_ID(0x01, 0x02), 0x00E2, REPORT_ID_CONSUMER_CTRL },/* f1 -> mute */
	{ FN_KEY_ID(0x01, 0x06), 0x00CD, REPORT_ID_CONSUMER_CTRL },/* f5 -> Play/ Pause */
	{ FN_KEY_ID(0x01, 0x09), 0x00E9, REPORT_ID_CONSUMER_CTRL },/* f3 -> Volume Up */
	{ FN_KEY_ID(0x02, 0x02), 0x00B6, REPORT_ID_CONSUMER_CTRL },/* f4 -> Previous Track */
	{ FN_KEY_ID(0x02, 0x06), 0x00B5, REPORT_ID_CONSUMER_CTRL },/* f6 -> Next Track */
	{ FN_KEY_ID(0x02, 0x0B), 0x00EA, REPORT_ID_CONSUMER_CTRL },/* f2 -> Volume Down */
	{ FN_KEY_ID(0x0A, 0x07), USAGE_ID_APPLICATION,	REPORT_ID_KEYBOARD_KEYS }, /* copilot -> application */
//	{ FN_KEY_ID(0x0A, 0x04), USAGE_ID_PRINT_SCREEN, REPORT_ID_KEYBOARD_KEYS },/* scr lock -> print screen */
#endif

#ifdef CONFIG_DPM_COLLABS_KEY_SUPPORT
    { COLLABS_KEY_ID(0x02, 0x07), 0x0004, REPORT_ID_DPM_INPUT }, /* Sharing Screen */
	{ COLLABS_KEY_ID(0x02, 0x0A), 0x0008, REPORT_ID_DPM_INPUT }, /* Chat */
	{ COLLABS_KEY_ID(0x08, 0x08), 0x0002, REPORT_ID_DPM_INPUT }, /* Video */
	{ COLLABS_KEY_ID(0x0B, 0x08), 0x0010, REPORT_ID_DPM_INPUT }, /* Mic Mute*/
#endif

#if CONFIG_DESKTOP_MAC_OS_KEYS_ENABLE
    { MAC_OS_KEY_ID(0x0A, 0x07), USAGE_ID_RIGHT_ALT,	REPORT_ID_KEYBOARD_KEYS }, /* copilot -> alt-r */
	{ MAC_OS_KEY_ID(0x0A, 0x0B), USAGE_ID_LEFT_ALT,		REPORT_ID_KEYBOARD_KEYS }, /* win-l   -> alt-l */
	{ MAC_OS_KEY_ID(0x0B, 0x06), USAGE_ID_LEFT_GUI,		REPORT_ID_KEYBOARD_KEYS }, /* alt-l   -> cmd-l */
	{ MAC_OS_KEY_ID(0x0B, 0x0A), USAGE_ID_RIGHT_GUI,	REPORT_ID_KEYBOARD_KEYS }, /* alt-r   -> cmd-r */
#endif
};
